
@domain= https://fishing-service-server-production.up.railway.app

###  lấy tất cả tài khoảng
GET {{domain}}/user
Content-Type: application/json
###  lấy thong tin cho trang dashboard
GET {{domain}}/user/dashboard
Content-Type: application/json


###  Đăng ký tài khoản mới
POST {{domain}}/user/register
Content-Type: application/json

{
 "data":{
"fullname":"Quản trị viên",
"email":"admin@gmail.com",
"password":"123456"
  }
}

###  Đăng nhập
POST {{domain}}/user/login
Content-Type: application/json

{
"data":{
    "email":"admin@gmail.com",
    "password":"123456"
}
}

###  Đăng ký và đăng nhập firebase
POST {{domain}}/user/firebase
Content-Type: application/json

{
"data":{

    "uid":"dsadsda",
    "avatar":"http://image.sdasda",
    "email":"namph2102@gmail.com",//Facebook ko có email
    "fullname":"Phạm Hoài Nam"
}
}


// lấy token để đăng nhập vào admin
###
POST {{domain}}/user/firstlogin
Authorization: Bearss eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWFuaHRoYW81OEBnbWFpbC5jb20iLCJpYXQiOjE2OTkzNTk4NTAsImV4cCI6MTY5OTYxOTA1MH0.qj7MhQzK9YX3HyiZC4V38UFSSPnktSfSh2x1FJOmja4


###  Thay đổi mật khẩu
POST {{domain}}/user/changepassword
Content-Type: application/json

{
"data":{
    "username":"dsadsda",
    "oldPassword":"1234567",
    "newPassword":"123456",
}
}

###  Xác thực tài khoản quên mật khẩu
POST {{domain}}/user/verify
Content-Type: application/json

{
"data":{
   
    "email":"admin@gmail.com",
 
}
}

###  Cập nhập tài khoản
PUT {{domain}}/user
Content-Type: application/json

{
"data":{
    "email":"admin@gmail.com",
    "fullname":"1234567",
    "phone":"0844669990",
    "address":"Dường hồ chí minh",
}
}

###  Cập nhập ảnh đại diện
PUT {{domain}}/user
Content-Type: application/json

{
"data":{
    "username":"admin@gmail.com",
    "avatar":"http://image.sdasda",
}
}

//-----------------------------------------------------------------------------------------------------------------------------------------------------------------

// coi trên link :https://dbdiagram.io/d/65462d377d8bbd646579a7d0;
// limk website: https://fishing-services.vercel.app/


###  danh sách Đơn hàng mua hàng
GET {{domain}}/order?limit=5&skip=0


###  Đơn hàng mua hàng
POST {{domain}}/order
Content-Type: application/json

{
   "data":{
      "order_id":1
   }
}
###  Đơn hàng mua hàng
POST {{domain}}/order
Content-Type: application/json

{
 "order":{
   "user_id":"xasxsxsxs",// user_id là di của tài khoảng  order
   "address":"xxx",// địa chỉ nhận hàng
   "discount_id":"xxx",// discount_id  là id của mã giảm giá có thể có hoặc ko => lúc người dùng nhập sẽ có api gửi lên để check mã đó tồn tại hay ko nha
   "fullname":"xxx",// Tên người nhận
   "paymentMethod":"Ví điện tử",//"Ví diện tử" || "COD" ||"Internet Banking"
   "phone":"xxx",
   "shipment":25000,// tiền ship 25000 hoặc là 0 ngàn
 },
 "order_detail":[
    {"id":"xx1","quantity":4},//id là id của product
    {"id":"xx2","quantity":4},
 ]

}

## lấy dữ liệu của tài khoản khi đăng nhập , đăng ký,login với token trường nào ko có thì để "" hoặc là  []
###  Thông tin tài khoảng
{
    "data":{
        "user":{
          "id":"xxx",
          "fullname":"xxx",
          "email":"xxx",
          "address":"xxx",
          "role":"xxx",
          "avatar":"xxx",
          "createAT":"xxx",
          "updatedAt":"xxx",
          "token":"xxx",
        },
        "notice":[  // danh sách thông báo 
        {
          "title":"xxx",
          "content":"xxx",
        }
        ],
        "order":[ // danh sách các đơn hàng đã đặt
        {
          "id":"xxx", // mã đơn hàng
          "fullname":"xxx",
          "address":"xxx",
          "discount_id":"1232", //discount_id là di của  đơn hàng chi tiết
          "address":"xxx",
          "shipment":"phương thức thanh toán",
          "createAt":"xxx",
          "updatedAt":"xxx",
          "status":1,// 1	Chờ xử lý 2	Đã kiểm duyệt 3	Đang giao hàng 4	thành công	5	thất bại	
         "shipment":0,
        }
        ]
        
    }
  
}

// khi anh click vào chi tiết đơn hàng thì em trả cho anh đơn hàng chi tiet

###
POST {{domain}}/order
Content-Type: application/json

{
    "data":{
      "order_id":"5"
    } 
}


# server trả về mảng sản phẩm có trong order đó khi xem sản phẩm chi tiết
###
POST {{domain}}/order
Content-Type: application/json
{
    "data":
   [
      {
         "id":"xxx",// mã sản phẩm
         "name":"xxx",// tên sản phẩm
         "quantity":5, // số luong
         "price":1000, // giá
         "imageUrl":"/d/sadsa",
         "description":"sdsasa dsa sadsa" // mô tả sản phẩm

     }
    ]
}
###
DELETE {{domain}}/user/1
Content-Type: application/json



//------------------------------------------------ Danh mục--------------------------------------------------------------



### Lấy tất cả danh much
GET {{domain}}/cate/

### Lấy 1 danh much
GET {{domain}}/cate/3


### Lấy 1 danh much theo slug
POST {{domain}}/cate/can-cau

### Lấy 1 danh much theo slug
POST {{domain}}/cate/seo/do-uong


### Tạo danh mục
POST {{domain}}/cate
Content-Type: application/json

{
   "data":  {
    "user_id": "2",
    "name": "Phạm hoài nam",
    "description": "oke quá oke",
    "imageUrl": "",
    "idPath": "222"
   }
}
### Chỉnh sửa danh mục sửa các trường theo bảng dbdram là dc id bắt buoc
PUT {{domain}}/cate
Content-Type: application/json

{
   "data":  {
    "id": "1",
    "name": "Phạm hoài nam 2",
    "description": "oke quá oke 1"
   }
}

### Xóa danh much5
DELETE  {{domain}}/cate/1


//------------------------------------------------ Sản phẩm---------------------------------------------------------------


### Lấy tất cả sản phẩm
GET {{domain}}/product/admin
### Lấy tất slug
GET {{domain}}/product/allslug
### Lấy tất cả sản phẩm

### tìm kiếm sản phẩm
POST {{domain}}/product/search
Content-Type: application/json

{
   "data":{
      "search":"can"
   }
}
### Lấy tất cả sản phẩm

GET {{domain}}/product/home

###
GET {{domain}}/product/bia-ha-noi
### Lấy 1 sản phẩm

GET {{domain}}/product/seo/can-cau-nam-my
### Lấy 1 sản phẩm

POST {{domain}}/product/updatesubimage
Content-Type: application/json

{
  "data":{
    "id":"6",
    "idPath":"krkqf4rcsnqs2lohjnqx"
  }
}
###
POST {{domain}}/product
Content-Type: application/json
### Tạo  sản phẩm
POST {{domain}}/product
Content-Type: application/json

{
   "data":  {
     "category_id":"3",
     "user_id":"2",
     "idPath":"san-pham",
     "price":35000,
     "name":"Quần Jean",
     "imageUrl":"/asdsada/dsadsa/saddsa",
      "listSubimages":"[]",
     "description":"Quần ngon lám",
     "selloff":"0",
     "cotnent":"saddsa",
   }
}
### Chỉnh sửa  sản phẩm
PUT {{domain}}/product
Content-Type: application/json

{
   "data":  {
    "id": 2,
    "description": "oke quá oke 1"
   }
}

### Xóa  sản phẩm
DELETE  {{domain}}/product/1

//------------------------------------------------Mã giảm giá---------------------------------------------------------------


###
GET  {{domain}}/discount?limit=5&skip=0
###//thêm
POST  {{domain}}/discount
Content-Type: application/json

{
   "data":  {
    "value": 10,
    "user_id": 1,
    "expirydate":""
   }
}
###
DELETE   {{domain}}/discount/12

### chỉnh sửa trang thái mã giảm giá
PUT  {{domain}}/discount
Content-Type: application/json

{
   "data":  {
    "id":"15",
    "value": "126"
   }
}

### KIỆM TRA MÃ
POST   {{domain}}/discount/verify
Content-Type: application/json

{
   "data":  {
    "code": "EMun7k"

   }
}



//------------------------------------------------ order ---------------------------------------------------------------### KIỆM TRA MÃ
###
GET   {{domain}}/order/3
Content-Type: application/json


//------------------------------------------------ Event ---------------------------------------------------------------

### Lấy tất cả Sự kiện
GET {{domain}}/event

### lấy cho trang home
POST {{domain}}/event/new

### lấy tat ca slug
POST {{domain}}/event/slug 

### Lấy 1 Sự kiện

GET {{domain}}/event/thuong-o-to-xin
### Tạo danh mục

POST {{domain}}/event
Content-Type: application/json

{
   "data":  {
    "user_id": 1,
    "title": "Sự kiện khui",
    "description": "Cày thâu đêm cùng Dự án đã làm toang quá",
    "imageUrl": "/assets/user-avt.png",
    "content": "d sad sad asd sad sa dsa dsa dsa dsa",
    "idPath":"dsadsadsa",
    "isEvent":true  
   
   }
}
### Chỉnh sửa danh mục sửa các trường theo bảng dbdram là dc id bắt buoc
PUT {{domain}}/event
Content-Type: application/json

{
   "data":  {
    "id": "1",
    "user_id": "Phạm hoài nam 2"
  
   }
}

### Xóa danh much5
DELETE  {{domain}}/cate/1


# ---------------------------------------- Liện hệ------------------------------------------### 


### lấy phân trang
GET {{domain}}/contact?limit=2&skip=0


### Tạo nới
POST {{domain}}/contact?limit=2&skip=5
Content-Type: application/json

{
   "data":{
      "fullname":"Phạm hoài nam",
      "email":"namanhthao59@gmail.com",
      "content":"Phạm hoài nam liên bạn mua câu",
      "phone":"0325024277"

   }
}

### Xóa
DELETE  {{domain}}/contact/2


# ---------------------------------------- thong bao------------------------------------------### 

### lấy hết
GET {{domain}}/notice?id=2&limit=2&skip=5



# ---------------------------------------- đánh giá ------------------------------------------### 

### lấy hết
GET {{domain}}/review?id=2&limit=2&skip=5
###
GET {{domain}}/review/3
### Thêm mới
POST {{domain}}/review
Content-Type: application/json

{
   "data":{
      "star":2,
      "user_id":2,
      "product_id":3,
      "content" : "Sản phâm tuyệt vời quá",
      "listImage" : ""
   }
}

### lxóa reviewDELETE  {{domain}}/review/1

